services:

  nair-mod3-zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    container_name: nair_mod3_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  nair-mod3-kafka:
    image: confluentinc/cp-kafka:7.7.0
    container_name: nair_mod3_kafka
    depends_on:
      - nair-mod3-zookeeper
    ports:
      - "29092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: nair-mod3-zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://nair-mod3-kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  nair-mod3-lambda-consumer:
    build: .
    image: nair-mod3-lambda-consumer
    container_name: nair_mod3_lambda_consumer
    depends_on:
      - nair-mod3-kafka
    # não precisa expor porta, é só consumer
